
POST http://localhost:5656/videos
Content-Type: application/json

{
  "title": "Video 01",
  "description": "this is the first video",
  "duration": 180
}

###

GET http://localhost:5656/videos

###

PUT http://localhost:5656/videos/
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Essa é a segunda descrição",
  "duration": 240
}

